name: Run Tests
on:
  push:
    branches:
      - develop
      - main

env:
  TEST_BACKEND: http://localhost:3000

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Start docker container
      working-directory: ./test
        run: |
          docker-compose run --rm pushme npx sequelize-cli db:migrate --env test
          docker-compose up -d

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Create Bundles
        run: npm run bundle

      - name: Get Docker Logs
        working-directory: ./test
        run: docker-compose logs

      - name: Run All Node.js Tests
        run: npm run test
